### ISSUE TITLE
task fails with 'docker is not a docker command'

### ISSUE THREAD

**Issue by rgcosma** [manojlds/gocd-docker#3]
Hi - I just tried a very simple test task using the plugin (downloaded the release jar) and while it does load, and the option appears in the task menu, the job once started just hangs indefinitely. I'm tailing the logs on both server and agent - nothing. Any hints on how to debug further?The docker service itself is running on the agent (Centos 7), the 'go' user is in the right group to run docker commands, I use a local repository from which I did test pull/build/push.

**Comment by rgcosma** [comment]
Fiddled with the settings until I did get some output in the logs, namely
2015-09-08 04:18:09,194 [loopThread] ERROR go.domain.builder.Builder:110 - Interaction with plugin with id 'docker-task' implementing 'task' extension failed while requesting for 'execute'. Reason: [null]
...
Caused by: java.lang.RuntimeException        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:317)
...
Caused by: java.lang.StackOverflowError
        at com.google.gson.stream.JsonWriter.string(JsonWriter.java:534)
...
And the task output in Go is
04:18:09.120 [go] Start to execute task: Plugin with ID: docker-task.
04:18:09.147 docker: 'docker' is not a docker command.
^^^ this is odd
04:18:09.148 See 'docker --help'.
04:18:09.171 dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
04:18:09.171 Error: failed to remove images: [docker-task:8]
04:18:09.194 Error: Interaction with plugin with id 'docker-task' implementing 'task' extension failed while requesting for 'execute'. Reason: [null]
04:18:09.218 [go] Current job status: failed.

**Comment by rgcosma** [comment]
also about /var/run/docker.sock: permission denied - the user 'go' does have privs to run/build images, needed a service restart. the error I have now is
08:37:41.370 docker: 'docker' is not a docker command.
08:37:41.371 See 'docker --help'.
08:37:41.402 Error response from daemon: No such image: docker-task:10
08:37:41.403 Error: failed to remove images: [docker-task:10]
08:37:41.442 Error: Interaction with plugin with id 'docker-task' implementing 'task' extension failed while requesting for 'execute'. Reason: [null]

**Comment by manojlds** [comment]
@rgcosma - thanks for the detailed analysis. There was a silly bug that introduced the command as `docker docker`. That was fixed in this - https://github.com/manojlds/gocd-docker/commit/b9ee3b46fdd33e3cdb6a7e02e26793a5f05034ca

I haven't looked at this in a while, I will run some sanity tests and upload a new build.

**Comment by zlmtk** [comment]
@manojlds, Hi, i have the same mistake,  do you know when your next release will be uploaded ?

**Comment by chromerobv** [comment]
any news on this ???

**Comment by bf16574403** [comment]
Hi All, 

Do we know of any updates to this app? Is it supported at all?

Please let me know.

bf.

**Comment by manojlds** [comment]
Hi @bf16574403  - I am the author of this plugin, and I haven't been looking at it recently. But will look into any issues you might have, and will also release a new version soon. Thanks!

**Comment by bf16574403** [comment]
Hi manojlds  , good to hear from you !!

I am keen to get in touch with you really need this app updated and support for a private registry.

Let me know how to get in touch.

bf.

**Comment by manojlds** [comment]
It took a while, but I finally got around to testing the plugin and creating a new release - https://github.com/manojlds/gocd-docker/releases/tag/0.1.27
